#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 IT Beratung Hermann GmbH

# Build a Wusel RPM. Compiles the release binary (FUSE) and the native Nautilus
# extension, stages the file tree, and runs rpmbuild. The result lands in
# ./dist/.
#
# Run this ON Fedora (needs: rpm-build, gcc, make, pkgconf, nautilus-devel,
# glib2-devel, fuse3-devel, and a Rust toolchain — mise is used if present, else
# the system cargo). To build from a macOS host without a Fedora machine, use
# scripts/podman-rpm.sh, which runs this inside a Fedora container.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO"

VERSION="$(grep -m1 '^version = ' Cargo.toml | cut -d'"' -f2)"
[ -n "$VERSION" ] || { echo "!! could not read version from Cargo.toml"; exit 1; }
echo ">> Building Wusel $VERSION RPM ..."

# Pinned toolchain via mise when available, else fall back to the system cargo.
if command -v mise >/dev/null 2>&1; then RUN=(mise exec --); else RUN=(); fi

# --- 1. Compile artefacts ---------------------------------------------------
echo ">> Compiling wusel (release, --features fuse) ..."
"${RUN[@]}" cargo build --release --features fuse -p wusel
TARGET_DIR="${CARGO_TARGET_DIR:-$REPO/target}"
BIN="$TARGET_DIR/release/wusel"
[ -x "$BIN" ] || { echo "!! binary not found at $BIN"; exit 1; }

echo ">> Compiling the Nautilus extension ..."
make -C integration/nautilus
SO="integration/nautilus/libwusel-nautilus.so"
[ -f "$SO" ] || { echo "!! extension not found at $SO"; exit 1; }

# --- 2. Stage the file tree (mirrors the final install layout) --------------
LIBDIR="$(rpm --eval '%{_libdir}')"                 # /usr/lib64 on x86_64
USERUNITDIR="/usr/lib/systemd/user"                 # stable; avoids systemd-rpm-macros
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
ROOT="$STAGE/wusel-$VERSION"                         # tarball top dir for %setup

install -Dm755 "$BIN"                    "$ROOT/usr/bin/wusel"
install -Dm644 packaging/rpm/wusel@.service "$ROOT$USERUNITDIR/wusel@.service"
install -Dm755 "$SO"                      "$ROOT$LIBDIR/nautilus/extensions-4/libwusel-nautilus.so"

emblemdir="$ROOT/usr/share/icons/hicolor/scalable/emblems"
install -d "$emblemdir"
install -m644 integration/nautilus/emblems/wusel-emblem-*.svg "$emblemdir/"

appdir="$ROOT/usr/share/applications"
dbusdir="$ROOT/usr/share/dbus-1/services"
provdir="$ROOT/usr/share/gnome-shell/search-providers"
install -d "$appdir" "$dbusdir" "$provdir"

# Search-provider launcher app + registration; the .service Exec is rewritten
# from the source default (/usr/local/bin) to the packaged path (/usr/bin).
install -m644 integration/gnome-search/at.itbh.Wusel.desktop "$appdir/"
install -m644 integration/gnome-search/wusel-search-provider.desktop "$provdir/"
sed 's#Exec=.*/wusel search-provider#Exec=/usr/bin/wusel search-provider#' \
    integration/gnome-search/at.itbh.Wusel.SearchProvider.service \
    > "$dbusdir/at.itbh.Wusel.SearchProvider.service"

# Cloud-provider (Nautilus sidebar) registration for the default account —
# generated by the freshly built binary so it never drifts from the code.
"$BIN" desktop install-provider --account default --dir "$appdir" >/dev/null
# install-provider runs update-desktop-database, which drops a mimeinfo.cache in
# the applications dir. That is not ours to ship (Fedora's desktop-file-utils
# trigger regenerates it on install), and rpmbuild rejects unpackaged files — so
# remove it from the staged tree.
rm -f "$appdir/mimeinfo.cache"

cp LICENSE README.md "$ROOT/"

# --- 3. rpmbuild ------------------------------------------------------------
RPMTOP="$(mktemp -d)"
trap 'rm -rf "$STAGE" "$RPMTOP"' EXIT
mkdir -p "$RPMTOP"/{SOURCES,SPECS,BUILD,RPMS,SRPMS}
tar -C "$STAGE" -czf "$RPMTOP/SOURCES/wusel-$VERSION.tar.gz" "wusel-$VERSION"
cp packaging/rpm/wusel.spec "$RPMTOP/SPECS/"

echo ">> rpmbuild ..."
rpmbuild --define "_topdir $RPMTOP" \
         --define "wusel_version $VERSION" \
         -bb "$RPMTOP/SPECS/wusel.spec"

mkdir -p "$REPO/dist"
find "$RPMTOP/RPMS" -name '*.rpm' -exec cp {} "$REPO/dist/" \;
echo ">> Done. RPM(s):"
ls -1 "$REPO/dist"/*.rpm
